# AsciiMath
ifndef::env-site[:status:]

An http://asciimath.org[AsciiMath] parser and MathML generator written in pure Ruby.

ifdef::status[]
[discrete]
## Status

image:https://travis-ci.org/pepijnve/asciimath.svg?branch=master["Linux Build Status", link="https://travis-ci.org/pepijnve/asciimath"]
image:https://img.shields.io/gem/v/asciimath.svg?label=gem%20version[Gem Version, link=https://rubygems.org/gems/asciimath]
endif::status[]

## Installation

Add this line to your application's Gemfile:

[source,ruby]
----
gem 'asciimath'
----

And then execute:

    $ bundle

Or install it yourself as:

    $ gem install asciimath

## Usage

### Library

First require the library.

[source,ruby]
----
require 'asciimath'
----

Then parse an AsciiMath string.

[source,ruby]
----
parsed_expression = AsciiMath.parse(asciimath)
----

The parsed expression is a set of nested Array and Hash objects.

This expression can then be converted to MathML.

[source,ruby]
----
math_ml = parsed_expression.to_mathml
----

The MathML code is returned as a String.

### Command line

The AsciiMath parser and MathML converter can be invoked via the command line as follows:

[source]
----
asciimath "an asciimath string"
----

This command will print out the generated MathML code on stdout.

## Contributing

. Fork it (https://github.com/pepijnve/asciimath/fork)
. Create your feature branch (`git checkout -b my-new-feature`)
. Commit your changes (`git commit -am 'Add some feature'`)
. Push to the branch (`git push origin my-new-feature`)
. Create a new Pull Request
