name: CI
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        ruby: [jruby, 2.3, 2.4, 2.5, 2.6, 2.7]
        os: [ubuntu-latest, macos-latest, windows-latest]
        rubyopt: [""]
        include:
          - ruby: 2.7
            os: ubuntu-latest
            rubyopt: "--enable-frozen-string-literal --debug-frozen-string-literal"

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Build
        run: bundle install --jobs 4 --retry 3
      - name: Test
        run: bundle exec rake test RUBYOPT="${{ matrix.rubyopt }}"
